//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tdtless10c.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tdtK22cnt3lession10cEntities : DbContext
    {
        public tdtK22cnt3lession10cEntities()
            : base("name=tdtK22cnt3lession10cEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TdtCategory> TdtCategory { get; set; }
        public virtual DbSet<TdtProduct> TdtProduct { get; set; }
    }
}
