//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tdtless10c.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TdtCategory
    {
        public TdtCategory() 
        {
        this.TdtProduct = new HashSet<TdtProduct>();
        }
        [Display(Name ="ma danh muc")]
        public int TdtID { get; set; }
        [Display(Name = "ten danh muc")]
        public string TdtCateName { get; set; }
        [Display(Name = "trang thai")]
        public Nullable<bool> TdtStatus { get; set; }
    }
}
