//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tdtless10c.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TdtProduct
    {
        public int TdtId2210900134 { get; set; }
        public string TdtProName { get; set; }
        public Nullable<int> TdtQty { get; set; }
        public Nullable<double> TdtPrice { get; set; }
        public Nullable<int> TdtCateId { get; set; }
        public Nullable<bool> TdtActive { get; set; }
    }
}
